import streamlit as st
import requests
from streamlit_lottie import st_lottie
from fpdf import FPDF
import wikipedia
import datetime

# ==========================================
# 1. CORE RESEARCH ENGINE
# ==========================================

def get_structured_research(topic):
    try:
        # Wikipedia se base data lena
        search_results = wikipedia.search(topic)
        if not search_results:
            return None
        
        page = wikipedia.page(search_results[0])
        content = {
            "title": page.title,
            "summary": page.summary,
            "sections": page.sections[:5], # Top 5 sections
            "full_text": page.content
        }
        return content
    except:
        return None

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 8)
        self.set_text_color(150)
        self.cell(0, 10, 'Academic Research Repository - Confidential', 0, 1, 'R')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI Research Engine', 0, 0, 'C')

def generate_professional_pdf(data):
    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # --- Title Section ---
    pdf.set_font('Arial', 'B', 28)
    pdf.set_text_color(20, 40, 80)
    pdf.cell(0, 40, data['title'], ln=True, align='C')
    
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100)
    pdf.cell(0, 10, f'Date of Publication: {datetime.date.today()}', ln=True, align='C')
    pdf.ln(20)

    # --- Abstract / Summary ---
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0)
    pdf.cell(0, 10, '1. EXECUTIVE SUMMARY', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 7, data['summary'].encode('latin-1', 'ignore').decode('latin-1'))
    pdf.ln(10)

    # --- Table of Contents (Simulated) ---
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '2. KEY TOPICS & ANALYSIS', ln=True)
    pdf.ln(5)

    # --- Sections & Body ---
    for i, section in enumerate(data['sections'], start=1):
        pdf.set_font('Arial', 'B', 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, f"  2.{i} {section}", ln=True, fill=True)
        pdf.ln(3)
        
        pdf.set_font('Arial', '', 11)
        # Extracting a snippet for each section (Simulated logic)
        section_text = f"Detailed analysis regarding {section} involving historical context, modern implementations, and technical specifications related to {data['title']}."
        pdf.multi_cell(0, 7, section_text)
        pdf.ln(5)

    return pdf.output(dest='S').encode('latin-1')

# ==========================================
# 2. ULTRA-MODERN UI (GLASSMORPHISM)
# ==========================================

st.set_page_config(page_title="AI Researcher Pro", layout="wide")

st.markdown("""
    <style>
    /* Gradient Background */
    .stApp {
        background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
        color: #f8fafc;
    }
    
    /* Frosted Glass Cards */
    div.stChatMessage {
        background: rgba(255, 255, 255, 0.03);
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 16px;
        margin-bottom: 15px;
    }
    
    /* Professional Sidebar */
    .css-163n192 {
        background-color: rgba(15, 23, 42, 0.8);
    }
    
    /* Inputs & Buttons */
    .stTextInput>div>div>input {
        background: rgba(255, 255, 255, 0.05);
        color: white;
        border-radius: 8px;
    }
    
    div.stButton > button {
        background: #3b82f6;
        color: white;
        border: none;
        padding: 12px 30px;
        border-radius: 8px;
        font-weight: 600;
        transition: all 0.3s ease;
    }
    
    div.stButton > button:hover {
        background: #2563eb;
        transform: translateY(-2px);
        box-shadow: 0 10px 15px -3px rgba(59, 130, 246, 0.5);
    }
    </style>
    """, unsafe_allow_html=True)

# ==========================================
# 3. INTERFACE LOGIC
# ==========================================

with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3413/3413535.png", width=80)
    st.title("Research Hub")
    st.markdown("---")
    st.write("📁 **Project Files**")
    uploaded_file = st.file_uploader("Upload context documents", type=['pdf', 'txt'])
    st.divider()
    st.caption("v2.0.4 Premium Academic Edition")

st.title("📑 Professional AI Assignment Engine")
st.write("Enter a topic to generate a structured, print-ready academic document.")

if prompt := st.chat_input("What would you like to research today?"):
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Synthesizing information from global databases..."):
            data = get_structured_research(prompt)
            
            if data:
                # Display on Screen
                st.header(data['title'])
                st.info("Abstract")
                st.write(data['summary'])
                
                st.markdown("### 🔍 Document Structure")
                for sec in data['sections']:
                    st.write(f"- {sec}")
                
                # PDF Generation
                pdf_bytes = generate_professional_pdf(data)
                
                st.divider()
                st.download_button(
                    label="📥 Download Professional PDF Report",
                    data=pdf_bytes,
                    file_name=f"Research_Report_{prompt.replace(' ','_')}.pdf",
                    mime="application/pdf"
                )
            else:
                st.error("Could not find enough academic data for this topic. Please try a more specific term.")
